/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#3c494e",
        "inverse-surface": "#263142",
        "secondary": "#006d3c",
        "secondary-container": "#85f6ad",
        "surface-tint": "#1960a3",
        "on-primary-container": "#e1ecff",
        "tertiary-container": "#5f6c72",
        "on-primary": "#ffffff",
        "surface-container-high": "#dee8ff",
        "inverse-primary": "#a2c9ff",
        "outline-variant": "#c1c7d2",
        "on-secondary-fixed-variant": "#00522c",
        "on-surface-variant": "#414750",
        "surface-container-low": "#f0f3ff",
        "on-surface": "#111c2c",
        "inverse-on-surface": "#ebf1ff",
        "outline": "#727782",
        "on-secondary": "#ffffff",
        "surface-container": "#e7eeff",
        "tertiary": "#475459",
        "on-primary-fixed": "#001c38",
        "on-tertiary-fixed": "#111d22",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d3e4ff",
        "secondary-fixed": "#88f9b0",
        "on-secondary-container": "#00723f",
        "on-background": "#111c2c",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#cfdaf1",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#00210f",
        "secondary-fixed-dim": "#6bdc96",
        "tertiary-fixed-dim": "#bcc8cf",
        "primary-fixed-dim": "#a2c9ff",
        "surface": "#f9f9ff",
        "surface-container-highest": "#d8e3fa",
        "tertiary-fixed": "#d8e4eb",
        "on-primary-fixed-variant": "#004881",
        "error": "#ba1a1a",
        "surface-variant": "#d8e3fa",
        "on-tertiary-container": "#e0edf4",
        "primary-container": "#2b6cb0",
        "primary": "#005394"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "md": "24px",
        "margin-mobile": "20px",
        "container-max": "800px",
        "gutter": "20px",
        "sm": "12px",
        "xs": "4px",
        "xl": "64px",
        "base": "8px"
      },
      fontFamily: {
        "headline-md": ["Atkinson Hyperlegible Next"],
        "label-caps": ["Public Sans"],
        "headline-lg-mobile": ["Atkinson Hyperlegible Next"],
        "body-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "headline-lg": ["Atkinson Hyperlegible Next"],
        "action-lg": ["Public Sans"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-caps": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "action-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
